name: Docker Actions

on: 
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: "hello actions"
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "learning lab use"
      
      - name: "meow"
        uses: ./.github/actions/cat-facts
        
      - name: "issue maker"
        uses: ./.github/actions/issue-maker
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          catFact: ${{steps.cat.outputs.fact}}
          issueTitle: "a cat fact for you"
